server:
  port: 8080
  servlet:
    context-path: /api/v1/

spring:
  profiles:
    active: prod

---
server:
  port: 8081

spring:
  config:
    activate:
      on-profile: dev1
---
server:
  port: 8082

spring:
  config:
    activate:
      on-profile: dev2